### PR TITLE
fix: missing dependency

### PR DESCRIPTION
**Pull request by vvo**
This project was completely failing otherwise, time for tests? L)

### CODE REVIEW

**Comment by vvo** [comment]
"time for integration test"

**Comment by mattdesl** [comment]
d'oh :+1: thanks

I need to start using `dependency-check` on publish..

**Comment by vvo** [comment]
did not know about dependency check, thanks

**Comment by vvo** [comment]
or maybe just build and test on travis

**Comment by mattdesl** [comment]
Yeah. Seems a bit tedious to unit test something like this... I'll have to think about how it could be done in Node.

**Pull request merged**
